server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: topic-exchange
  queue: stock.alert.queue
  routing-key: stock.alert